# Generated by Django 5.1.4 on 2024-12-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=45)),
                ('organizer', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StageEventShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('stage_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.stageevent')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('customer', models.CharField(max_length=45)),
                ('no_of_seats', models.IntegerField()),
                ('stage_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.stageevent')),
            ],
        ),
    ]
